/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tw_edu_ntu_lads_chouguting_java_cipers_KyberEngine */

#ifndef _Included_tw_edu_ntu_lads_chouguting_java_cipers_KyberEngine
#define _Included_tw_edu_ntu_lads_chouguting_java_cipers_KyberEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tw_edu_ntu_lads_chouguting_java_cipers_KyberEngine
 * Method:    kemKeypair
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_tw_edu_ntu_lads_chouguting_java_cipers_KyberEngine_kemKeypair
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     tw_edu_ntu_lads_chouguting_java_cipers_KyberEngine
 * Method:    kemEncapsulate
 * Signature: ([B[B[B[B)V
 */
JNIEXPORT void JNICALL Java_tw_edu_ntu_lads_chouguting_java_cipers_KyberEngine_kemEncapsulate
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     tw_edu_ntu_lads_chouguting_java_cipers_KyberEngine
 * Method:    kemDecapsulate
 * Signature: ([B[B[B)V
 */
JNIEXPORT void JNICALL Java_tw_edu_ntu_lads_chouguting_java_cipers_KyberEngine_kemDecapsulate
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     tw_edu_ntu_lads_chouguting_java_cipers_KyberEngine
 * Method:    pkeKeypair
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_tw_edu_ntu_lads_chouguting_java_cipers_KyberEngine_pkeKeypair
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     tw_edu_ntu_lads_chouguting_java_cipers_KyberEngine
 * Method:    pkeEncrypt
 * Signature: ([B[B[B[B)V
 */
JNIEXPORT void JNICALL Java_tw_edu_ntu_lads_chouguting_java_cipers_KyberEngine_pkeEncrypt
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     tw_edu_ntu_lads_chouguting_java_cipers_KyberEngine
 * Method:    pkeDecrypt
 * Signature: ([B[B[B)V
 */
JNIEXPORT void JNICALL Java_tw_edu_ntu_lads_chouguting_java_cipers_KyberEngine_pkeDecrypt
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
