/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tw_edu_ntu_lads_chouguting_java_cipers_KyberEngine */

#ifndef _Included_tw_edu_ntu_lads_chouguting_java_cipers_KyberEngine
#define _Included_tw_edu_ntu_lads_chouguting_java_cipers_KyberEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tw_edu_ntu_lads_chouguting_java_cipers_KyberEngine
 * Method:    keypair
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_tw_edu_ntu_lads_chouguting_java_cipers_KyberEngine_keypair
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     tw_edu_ntu_lads_chouguting_java_cipers_KyberEngine
 * Method:    encapsulate
 * Signature: ([B[B[B[B)V
 */
JNIEXPORT void JNICALL Java_tw_edu_ntu_lads_chouguting_java_cipers_KyberEngine_encapsulate
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     tw_edu_ntu_lads_chouguting_java_cipers_KyberEngine
 * Method:    decapsulate
 * Signature: ([B[B[B)V
 */
JNIEXPORT void JNICALL Java_tw_edu_ntu_lads_chouguting_java_cipers_KyberEngine_decapsulate
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
